show databases;
create database if not exists schemar;
use schemar;
create table if not exists watch ( 
    watchid int(4) primary key,
    watchname varchar(20) not null,
    type varchar(7) default 'unisex',
    qty_store int(4),
    unitprice int(10)
    );
desc watch;
insert into watch values (1,'casio',null,2,5000);
insert into watch(watchid,watchname,qty_store,unitprice) values (2,'g-shock',3,6000);
insert into watch(watchid,watchname,type,qty_store,unitprice) values (3,'abc','male',1,2000);
select * from watch;
select * from watch where type='unisex';
select watchname from watch where type='unisex';

-- USE schemar;
DROP TABLE IF EXISTS PERSON_DETAILS;
DROP VIEW IF EXISTS KKD;
CREATE TABLE IF NOT EXISTS PERSON_DETAILS (
NAME VARCHAR(255),
AGE INT NOT NULL,
PH_NO INT(10),
EMAIL_ADDRESS VARCHAR(255) 
);
INSERT INTO PERSON_DETAILS VALUES ('ABC',17,1234567890,'ABC@GMAIL.COM');
INSERT INTO PERSON_DETAILS VALUES ('BCD',15,0123456789,'BCD@GMAIL.COM');
-- SELECT * FROM PERSON_DETAILS;
ALTER TABLE PERSON_DETAILS ADD ADDRESS VARCHAR(255) DEFAULT 'MARTHOMA PUBLIC SCHOOL' ;
ALTER TABLE PERSON_DETAILS MODIFY AGE DECIMAL(3,1);
-- ALTER TABLE PERSON_DETAILS DROP PH_NO;
-- ALTER TABLE PERSON_DETAILS DROP EMAIL_ADDRESS;
INSERT INTO PERSON_DETAILS VALUES ('ABC',16.0,1234567890,'ABC@GMAIL.COM','KAKKANAD'); 
INSERT INTO PERSON_DETAILS VALUES ('BC',15.3,012345678,'BD@GMAIL.COM','EDACHIRA');
INSERT INTO PERSON_DETAILS VALUES ('ABC',13.2,1234567890,'ABC@GMAIL.COM');
INSERT INTO PERSON_DETAILS VALUES ('BCD',12.5,012345689,'BCD@GMAIL.COM','ERNAKULAM'), ('AC',17.8,123467890,'AC@GMAIL.COM','KOCHI'),('BD',18.3,0123456789,'BCD@GMAIL.COM','KAKKANAD'),('BC',17.9,123467890,'ABC@GMAIL.COM','ERNAKULAM'),('ACD',15.1,0123456789,'BD@GMAIL.COM','KAKKANAD'); -- Variation Showing How 2 Add Multiple Values into the Database at Once
SELECT * FROM PERSON_DETAILS;
SELECT * FROM PERSON_DETAILS WHERE ADDRESS='KAKKANAD';
SELECT NAME,AGE FROM PERSON_DETAILS WHERE ADDRESS='KAKKANAD';
CREATE VIEW KKD AS 
            SELECT NAME,AGE FROM PERSON_DETAILS WHERE ADDRESS='KAKKANAD';
-- SHOW TABLES;
SELECT * FROM KKD;
DROP VIEW IF EXISTS KKD;
SHOW TABLES;
-- DROP DATABASE SCHEMAR;
SELECT * FROM PERSON_DETAILS ORDER BY ADDRESS ASC; -- DESC
SELECT * FROM PERSON_DETAILS ORDER BY AGE DESC; -- ASC
UPDATE PERSON_DETAILS SET NAME='ROHITH' WHERE NAME="AC" AND AGE=17.8;
SELECT * FROM PERSON_DETAILS;